### ISSUE TITLE
Runtime VQE job gets cancelled after running too long

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#173] opened 2022-02-28 20:37 UTC
**Describe the bug**
I have been trying to run this tutorial https://github.com/Qiskit-Partners/qiskit-runtime/blob/main/tutorials/vqe.ipynb, but whenever I reach the stage of running  Runtime VQE: VQEProgram, the job runs for about five hours and then gets canceled ("ran too long"). The only change made in the code is using the backends available to me (free account with access to only five qubit machines). This problem persists for all available systems and remains even when the number of shots is changed from 1024 to 100. See screenshots below for reference.
![Screenshot (270)](https://user-images.githubusercontent.com/83826611/156027976-853ac21a-e3fb-4213-b42c-2dc25908f546.png)
![Screenshot (271)](https://user-images.githubusercontent.com/83826611/156028001-a8379010-e18a-4c61-8929-c24a2d17b70c.png)

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

Transferred from https://github.com/Qiskit-Partners/qiskit-runtime/issues/100
cc @kalpakghosh

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment] 2022-05-16 02:31
Closing as duplicate of #195 since the other issue has more info.

**Closed by rathishcholarajan** 2022-05-16 02:31 UTC
Labels: bug
