### ISSUE TITLE
Cannot set max session time larger than program cost

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#471] opened 2022-08-16 22:55 UTC
**Describe the bug**
A session is supposed to allow multiple primitive calls to by-pass the queue, provided the session is kept active.  The default time for a session appears to be 10 minutes, however most real workflows go well beyond that limit.  To the best of my knowlege a session is supposed to allow for up to 8 hours of QPU access like the runtimes of today.  However, trying to set that gives the error:

"code":"bad_request","message":"provided cost (28800) exceeds program cost (10000)"

indicating that the max time is about 2.75 hours; the max runtime of the sampler that I am calling.

**Steps to reproduce**

**Expected behavior**
The session should not have a max runtime bound by the underlying program call

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by renier** [comment] 2022-08-17 00:47
There is something strange about your program. Can you paste it?

All of the jobs in the session for the job_id you provided have a cost of 900 seconds. Which only should happen if you override it to that value.

**Comment by nonhermitian** [comment] 2022-08-17 00:51
I cannot paste the full circuit generation code, but my session calling looks like:

```python
jobs = []

options = Options(backend="ibm_geneva")

session =  Session(service=service)
sampler = Sampler(session=session, options=options)
for circs in mapped_circs:
    job = sampler.run(circs)
    jobs.append(job)

**Comment by renier** [comment] 2022-08-18 18:25
The spirit of this issue which is "cannot set max session time larger than program cost" is by design. The actual bug mixed in here is #475 , but right now the sampler sessions have a maximum of 2.78 hours imposed by the system.  It is bound by the primitive as we support it.

If we should not bound it that way, we can certainly explore that option in the service. This would not be a change in the provider.

**Comment by nonhermitian** [comment] 2022-08-18 20:23
I think it would be more natural if the max time was at the session level, and then the primitives within that session would be bounded by this outer-scope limit.  That way I can define my session time to be something like 8hrs, and I can run as many primitives as I like within this limit, being kicked off if I leave the system idle.  One could of course still set the per-primitive limits if so desired.

**Comment by renier** [comment] 2022-08-22 22:10
being fixed on the server side.

**Comment by kt474** [comment] 2022-08-24 14:32
Fixed on server side, closing

**Closed by kt474** 2022-08-24 14:32 UTC
