### ISSUE TITLE
Local simulator backend APIs do not match that of real processor backend objects

### ISSUE THREAD

**Issue by KPRoche** [Qiskit/qiskit-ibm-runtime#1676] opened 2024-05-14 00:24 UTC
With the cloud simulators going away May 15, the [Migration Guides](https://docs.quantum.ibm.com/api/migration-guides/local-simulators#migrate-to-local-simulators) encourage users to switch to local testing: 
> Quantum simulators should be used to help develop and test programs before fine-tuning them and sending them to quantum hardware. Local simulators can do this with good performance and efficiency.

This is especially important for users like me which only have limited Open Plan access to the real processors, so making sure program flow works before accessing a real backend is critical.
Unfortunately, the attrributes and methods of the local simulators objects __do not match__  those of the real IBMbackend object; for instance, the FakeBackends do not have the _backend.simulator_ attribute nor the _backend.status()_ method, and Aer simulators do not have the simulator attribute.

**Steps to reproduce**
In a python session load the QiskitRuntimeService and instantiate a connection to your account, then create a connection to a real backend, a fakebackend, and an aer simulator. The APIs do not match

> from qiskit_ibm_runtime import QiskitRuntimeService      
> from qiskit_ibm_runtime.fake_provider import FakeManilaV2
> from qiskit_aer import Aer, AerSimulator
> service = QiskitRuntimeService()
> realbackend = service.least_busy(operational=True, simulator=False)
> fakebackend = FakeManilaV2()
> aersimulator = AerSimulator.from_backend(realbackend)
> 
> realbackend.simulator
> False
> realbackend.status().operational
> True
> realbackend.status().pending_jobs
> 1
> fakebackend.simulator
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'FakeManilaV2' object has no attribute 'simulator'
> fakebackend.status().operational
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'FakeManilaV2' object has no attribute 'status'
> aersimulator.simulator
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'AerSimulator' object has no attribute 'simulator'
> aersimulator.status().operational
> True
> aersimulator.status().pending_jobs
> 0
> 

What happens: 
The fake backend throws an error if you attempt to access the **simulator** attribute or attempt to use the **status()** method.
The Aer simulator _does_ return results from the **status()** method, but does not have the *simulator* attribute
These are just a few examples
**Expected behavior**
If the local testing backends are supposed to be used for code development before programatically accessing the real IBM Quantum devices, they should return responses for all the attributes and methods of the **IBMBackend** object

**Suggested solutions**
Fill in the missing attributes and methods so local testing backend objects match the IBMBackend objects

**Additional Information**

- **qiskit-ibm-runtime version**:
1
- **Python version**:
- 3.9.18
- **Operating system**:
CentOS Stream 9

**Comment by yaelbh** [comment] 2024-05-15 06:09
This reminds me of a [similar issue that I once opened](https://github.com/Qiskit/qiskit-aer/issues/1567). I don't know how much of that old issue is still relevant.

**Comment by KPRoche** [comment] 2024-05-15 17:46
> This reminds me of a [similar issue that I once opened](https://github.com/Qiskit/qiskit-aer/issues/1567). I don't know how much of that old issue is still relevant.

Some of it definitely is still relevant. I only pulled out a sample of the differences between the objects

**Comment by jyu00** [comment] 2024-07-02 16:44
Duplicate of #1605

**Closed by jyu00** 2024-07-02 16:44 UTC
Labels: bug
