### ISSUE TITLE
job.status() occasionally gets stuck

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#317] opened 2022-05-10 18:57 UTC
**Describe the bug**

`job.status()` occasionally gets stuck. It doesn't always happen, but I've seen it twice today. Here's the relevant qiskit-ibm-runtime log:

```
runtime_job._stream_results:DEBUG:2022-05-10 13:56:53,963: Start result streaming for job c9taepfoqool4ftobu60
session._log_request_info:DEBUG:2022-05-10 13:56:53,963: Endpoint: https://runtime-us-east.quantum-computing.ibm.com/jobs/c9taepfoqool4ftobu60. Method: GET. 
runtime.job_get:DEBUG:2022-05-10 13:56:54,042: Runtime job get response: {'id': 'c9taepfoqool4ftobu60', 'hub': 'ibm-q-internal', 'group': 'dev-sys-software', 'project': 'internal-test', 'backend': 'ibmq_dublin', 'state': {'status': 'Queued'}, 'params': {'custom_circuits': None, 'use_job_builder': True, 'bad_run_jobs': 0, 'num_large_jobs': 0, 'num_slow_jobs': 0, 'num_snail_jobs': 0, 'bad_compile_jobs': 0, 'run_options': None, 'num_fast_jobs': 1}, 'program': {'id': 'aot-test-l6kVeEwMN3'}, 'created': '2022-05-10T17:56:53.689785Z', 'runtime': 'qiskit-program:62a0ae0', 'status': 'Queued'}
base.on_open:DEBUG:2022-05-10 13:56:54,235: Websocket connection established for job c9taepfoqool4ftobu60
session._log_request_info:DEBUG:2022-05-10 14:01:54,091: Endpoint: https://runtime-us-east.quantum-computing.ibm.com/jobs/c9taepfoqool4ftobu60. Method: GET. 
base.on_close:DEBUG:2022-05-10 14:01:56,057: Websocket connection for job c9taepfoqool4ftobu60 closed. status code=1000, message=
base.stream:DEBUG:2022-05-10 14:01:56,057: Websocket run_forever finished.
base.disconnect:DEBUG:2022-05-10 14:01:56,057: Client closing websocket connection with code None.
```

As you can see, the first GET that happens at `13:56:53,963` returns with a response. The second GET at `14:01:54,091`, however, appears to be stuck. I'm not sure if the fact that the job is terminating (2s after the GET) is a contributing factor. More interestingly, the `job.status()` call never timed out even after an hour, which makes me think it's an issue in qiskit-ibm-runtime and not the server code. 

**Steps to reproduce**

My program submits a job then does something like

```
    for _ in range(total_iteration):
        try:
            # Spit out messages periodically
            logger.info(f"Waiting for job {get_job_id(job)} to finish. "
                        f"Current status is {job.status()}")
            return job.result(log_message_time)
        # TODO: Use JobTimeoutError until qiskit-ibm-runtime 316 is fixed
        except TimeoutError:
            pass
```

This code gets stuck at `job.status()` 2/4 times. 

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.4.0
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment] 2022-05-12 15:52
Thanks for identifying this, will prioritize this for this quarter.

**Comment by jyu00** [comment] 2022-05-17 15:47
FWIW, this happened again today. I interrupted the process and the traceback is 
```
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/qiskit_ibm_runtime/runtime_job.py", line 210, in status
    self._set_status_and_error_message()
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/qiskit_ibm_runtime/runtime_job.py", line 298, in _set_status_and_error_message
    response = self._api_client.job_get(job_id=self.job_id)
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/qiskit_ibm_runtime/api/clients/runtime.py", line 201, in job_get
    response = self._api.program_job(job_id).get()
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/qiskit_ibm_runtime/api/rest/program_job.py", line 50, in get
    return self.session.get(self.get_url("self")).json()
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/qiskit_ibm_runtime/api/session.py", line 264, in request
    response = super().request(method, final_url, headers=headers, **kwargs)
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jessieyu/.pyenv/versions/aot-test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/jessieyu/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
```

Job id is `ca1rjqc4bbdf8kpcdobg`

**Comment by jyu00** [comment] 2022-05-23 21:25
bump - still seeing this

**Comment by rathishcholarajan** [comment] 2022-05-24 03:23
I tried several times with below code and set job.result timeout as low as 0.1 secs. But couldn't reproduce it.
```python
from qiskit import QuantumCircuit
from concurrent.futures import TimeoutError
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(channel="ibm_quantum")

# Create a circuit.
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()

# Set the "sampler" program inputs
inputs = {
    'circuits': qc,
    'circuit_indices': [0]
}

backend = service.least_busy(min_num_qubits=2, simulator=False)

# Configure backend options
options = {'backend_name': backend.name}

# Execute the circuit using the "sampler" program.
job = service.run(program_id="sampler",
                  options=options,
                  inputs=inputs,
                 )
for _ in range(1000):
    try:
        # Spit out messages periodically
        print(f"Waiting for job {job.job_id} to finish. "
              f"Current status is {job.status()}")
        print(job.result(0.1))
        break
    # TODO: Use JobTimeoutError until qiskit-ibm-runtime 316 is fixed
    except TimeoutError:
        pass
```
Output
```
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.QUEUED
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.RUNNING
Waiting for job ca64rogkgt9h5mun5d90 to finish. Current status is JobStatus.DONE
{'quasi_dists': [{'00': 0.19825, '01': 0.23425, '10': 0.259, '11': 0.3085}], 'metadata': [{'header_metadata': {}, 'shots': 4000}]}
```

@renier Using @jyu00's logs above could we check what happened to this call, from server logs?
```
session._log_request_info:DEBUG:2022-05-10 14:01:54,091: Endpoint: https://runtime-us-east.quantum-computing.ibm.com/jobs/c9taepfoqool4ftobu60. Method: GET. 
```

@jyu00 What is the timeout you use for job.result? Could you paste your program if you can reproduce it consistently?

**Comment by jyu00** [comment] 2022-05-24 12:21
My timeout is set at 300s. My test randomly generates 5-10 jobs, each in terms generate 5-10 small, medium, and large jobs each. Then it uses [the code listed early](https://github.com/Qiskit/qiskit-ibm-runtime/issues/317#issue-1231567151) to poll for status. 

Small jobs use circuit:
```
    qubits = 5
    circuit = QuantumVolume(qubits, seed=42)
    circuit.measure_all()
    return transpile(circuit, backend)
```

Medium jobs use the same circuit but with max shots.

Large circuit:
```
    qubits = backend.configuration().num_qubits
    qx = random_circuit(num_qubits=qubits, depth=10, measure=True, seed=random.randint(0, 1000))

    qx = transpile(qx, backend)
    return [qx]*min(backend.configuration().max_experiments, 10)
```

**Comment by renier** [comment] 2022-05-25 00:35
@rathishcholarajan Found the log on the server side. But it looks normal:
```
May 10 13:01:54 api-6568cb84cf-zhsxv api info {"level":"info","correlation-id":"c9tah4j9rr0udeit6880","method":"GET","path":"/jobs/c9taepfoqool4ftobu60","remote_addr":"172.30.64.95","latency_ms":5,"status_code":200,"user_agent":"python-requests/2.26.0","user_id":"xxxxxxxx","country":"US","Service-CRN":"","action":"job.read","time":"2022-05-10T18:01:54Z"}
```

**Comment by jyu00** [comment] 2022-08-08 21:15
I uncommented the code that checks for status to see if this has been fixed, and it hit the same issue again:


```
base.stream:DEBUG:2022-08-08 17:01:23,141: Starting new websocket connection: wss://runtime-us-east.quantum-computing.ibm.com/stream/jobs/cbonj8gn3g5bfom3o2rg using proxy {}
session._log_request_info:DEBUG:2022-08-08 17:01:23,142: Endpoint: https://runtime-us-east.quantum-computing.ibm.com/jobs/cbonj8gn3g5bfom3o2rg. Method: GET. 
runtime.job_get:DEBUG:2022-08-08 17:01:23,231: Runtime job get response: {'id': 'cbonj8gn3g5bfom3o2rg', 'hub': 'ibm-q-internal', 'group': 'dev-sys-software', 'project': 'internal-test', 'backend': 'ibmq_manila', 'state': {'status': 'Queued'}, 'params': {'num_large_jobs': 0, 'num_snail_jobs': 0, 'custom_circuits': None, 'run_options': None, 'num_fast_jobs': 1, 'num_slow_jobs': 0, 'bad_run_jobs': 0, 'use_job_builder': True, 'bad_compile_jobs': 0}, 'program': {'id': 'aot-test-q350Lml98R'}, 'created': '2022-08-08T21:01:22.969092Z', 'runtime': 'qiskit-program:ba8febd', 'cost': 300, 'status': 'Queued'}
TestAoTJobs.get_job_result:INFO:2022-08-08 17:01:23,232: Waiting for job cbonj8gn3g5bfom3o2rg to finish. Current status is JobStatus.QUEUED
base.on_open:DEBUG:2022-08-08 17:01:23,337: Websocket connection established for job cbonj8gn3g5bfom3o2rg
session._log_request_info:DEBUG:2022-08-08 17:06:23,240: Endpoint: https://runtime-us-east.quantum-computing.ibm.com/jobs/cbonj8gn3g5bfom3o2rg. Method: GET. 
```

The first GET at 17:01:23,142 returned immediately but the second one never did (sent at 17:06 and it's now 17:14)

**Comment by daka1510** [comment] 2022-12-13 16:15
@ChitsimranGill no longer able to reproduce it. Closing.

**Closed by daka1510** 2022-12-13 16:15 UTC
Labels: bug, priority: high
