### ISSUE TITLE
Unable to retrieve job result. QiskitError: "The QPY format version being read, 10, isn\'t supported by this Qiskit version. Please upgrade your version of Qiskit to load this QPY payload

### ISSUE THREAD

**Issue by raybeecham** [Qiskit/qiskit-ibm-runtime#1332] opened 2024-01-24 07:05 UTC
### Environment

- **0.45.2**: 
- **3.10.13**: 
- **Windows 11**: 

### What is happening?

I am running through Q-CTRLs Get Started guide here: https://docs.q-ctrl.com/q-ctrl-embedded/ibm/get-started. When I run the code below:

```
from qiskit_ibm_runtime import Sampler, Options

shot_count = 2048

backend = service.backend(backend_name)
options = Options()
options.execution.shots = shot_count
sampler = Sampler(backend=backend, options=options)

q_ctrl_result = sampler.run(circuit_qis).result()
q_ctrl_probabilities = (
    q_ctrl_result.quasi_dists[0]
    .nearest_probability_distribution()
    .binary_probabilities(num_bits=11)
)
```

I receive this error: 'Unable to retrieve job result. QiskitError: "The QPY format version being read, 10, isn\'t supported by this Qiskit version. Please upgrade your version of Qiskit to load this QPY payload'

### How can we reproduce the issue?

To reproduce the errors follow the guide here for the Get Started documentation: https://docs.q-ctrl.com/q-ctrl-embedded/ibm/get-started. Enter your IBM Cloud API keys and IBM Cloud CRN and follow the steps up the this section of code:

```
from qiskit_ibm_runtime import Sampler, Options

shot_count = 2048

backend = service.backend(backend_name)
options = Options()
options.execution.shots = shot_count
sampler = Sampler(backend=backend, options=options)

q_ctrl_result = sampler.run(circuit_qis).result()
q_ctrl_probabilities = (
    q_ctrl_result.quasi_dists[0]
    .nearest_probability_distribution()
    .binary_probabilities(num_bits=11)
)
```

### What should happen?

The results should be returned to the device, and then you can plot the results and calculate the success probability, which estimates the probability that a single execution (shot) of the circuit will yield a solution.

**Comment by raybeecham** [comment] 2024-01-24 14:51
@ElePT Got it, is there anything I can do in the interim? Thanks!

**Comment by 1ucian0** [comment] 2024-01-24 14:59
issue moved. No need to submit a new issue

**Comment by rowenwu** [comment] 2024-01-24 22:23
Hi @raybeecham, thanks for the detailed message. I also responded to you over Intercom (you should see it in your email inbox). As ElePT mentioned, the issue is due to a version mismatch between a newer version of Qiskit/QPY and `qiskit-ibm-runtime`. As a workaround, can you try downgrading `qiskit-ibm-runtime` to version 0.7.2?

**Comment by raybeecham** [comment] 2024-01-24 22:54
I saw it and am planning to downgrade the runtime and test it. Thank you
for responding quickly. Any chance you know when the upgrade might happen?
Thanks!

**Comment by kt474** [comment] 2024-01-24 23:08
Just a minor correction - the workaround would be downgrading the `qiskit-ibm-provider` version to 0.7.2, that's where the QPY module currently lives. Sorry for the confusion

**Comment by raybeecham** [comment] 2024-01-25 18:25
One additional question. I've been running this solution since this
morning. Do you know why the run time and queue time is so long?

**Comment by DLPQ** [comment] 2024-01-26 23:54
Wanted to add that I had the same error and downgrading `qiskit-ibm-provider` version to 0.7.2 resolved the issue. Just so other people save one search, you can do this with ` pip install --force-reinstall -v 'qiskit-ibm-provider==0.7.2'`.

**Comment by rowenwu** [comment] 2024-01-27 03:44
Thanks @DLPQ for sharing the solution!

**Comment by raybeecham** [comment] 2024-01-29 15:04
Chiming in to let everyone know this solution did work for me. Thank you everyone for your help.

**Comment by kt474** [comment] 2024-01-29 16:17
Closing as resolved, Thanks everyone!

**Closed by kt474** 2024-01-29 16:17 UTC
Labels: bug
